import {readFileSync,writeFileSync,mkdirSync,cpSync,rmSync} from 'node:fs';
import {join} from 'node:path';
const html=readFileSync('dist/index.html','utf8');
const out='theme-package';
rmSync(out,{recursive:true,force:true});
mkdirSync(out,{recursive:true});
cpSync('dist/assets',join(out,'assets'),{recursive:true});
const script=[...html.matchAll(/<script\b[^>]*src="([^"]+)"[^>]*><\/script>/g)].map(m=>m[1]);
const css=[...html.matchAll(/<link\b[^>]*href="([^"]+\.css)"[^>]*>/g)].map(m=>m[1]);
if(!script.length||!css.length||[...script,...css].some(p=>!p.startsWith('/theme/vv-theme/assets/')))throw Error('Unexpected Vite asset paths');
const title='{{ $title }}';
const blade='<!doctype html>\n<html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+title+'</title>\n'+css.map(p=>'<link rel="stylesheet" href="'+p+'">').join('\n')+'\n'+script.map(p=>'<script type="module" crossorigin src="'+p+'"></script>').join('\n')+'\n</head><body><script>window.routerBase="/";window.settings={title:@json($title),assets_path:"/theme/vv-theme/assets",version:@json($version),description:@json($description),logo:@json($logo),theme:{color:@json($theme_config["theme_color"] ?? "default")},background_url:@json($theme_config["background_url"] ?? "")};</script><div id="root"></div>{!! $theme_config["custom_html"] ?? "" !!}</body></html>\n';
writeFileSync(join(out,'dashboard.blade.php'),blade);
writeFileSync(join(out,'config.json'),JSON.stringify({name:'vv-theme',version:process.env.THEME_VERSION||'0.2.2',description:'React live user portal for TXBoard',author:'ANRCM0',compatibility:{txboard:'*'},configs:[{label:'主题色',field_name:'theme_color',field_type:'select',select_options:{default:'默认青色',blue:'蓝色',darkblue:'深蓝色'},default_value:'default'},{label:'背景图片 URL',field_name:'background_url',field_type:'input'},{label:'自定义 HTML（管理员可信内容）',field_name:'custom_html',field_type:'textarea',public:false}]},null,2)+'\n');
console.log('TXBoard package staged:',script.length,'scripts,',css.length,'stylesheets');
